pub mod json_location_schema {
    /// Generated by https://quicktype.io
    use std::collections::HashMap;

    extern crate serde_json;

    use serde::{Deserialize, Serialize};

    pub type LocationSchema = Vec<LocationSchemaElement>;

    #[derive(Serialize, Deserialize, Debug)]
    pub struct LocationSchemaElement {
        #[serde(rename = "name")]
        pub name: String,

        #[serde(rename = "local_names")]
        pub local_names: Option<HashMap<String, String>>,

        #[serde(rename = "lat")]
        pub lat: f64,

        #[serde(rename = "lon")]
        pub lon: f64,

        #[serde(rename = "country")]
        pub country: String,

        #[serde(rename = "state")]
        pub state: String,
    }
}
